<#
.SYNOPSIS
    VMware Snapshot Management Tool
    
.DESCRIPTION
    Manages VM snapshots including creation, deletion, consolidation,
    and reporting for VMware vSphere environment.
    
.PARAMETER Operation
    Operation to perform: Create, Delete, Report, Cleanup
    
.PARAMETER vCenter
    vCenter server address
    
.PARAMETER VMName
    Target VM name(s) for snapshot operations
    
.EXAMPLE
    .\Snapshot-Manager.ps1 -Operation Report -vCenter "vcenter.local"
    
.NOTES
    Author: Aykut Yıldız  
    Version: 1.5
    Date: 2024-11-21
    GitHub: https://github.com/infrawisetech/IT-Admin-Toolkit
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("Create", "Delete", "Report", "Cleanup", "Consolidate")]
    [string]$Operation,
    
    [Parameter(Mandatory=$true)]
    [string]$vCenter,
    
    [Parameter(Mandatory=$false)]
    [string[]]$VMName,
    
    [Parameter(Mandatory=$false)]
    [string]$SnapshotName = "Snapshot_$(Get-Date -Format 'yyyyMMdd')",
    
    [Parameter(Mandatory=$false)]
    [string]$Description = "Created by PowerShell Automation",
    
    [Parameter(Mandatory=$false)]
    [int]$DaysOld = 7,
    
    [Parameter(Mandatory=$false)]
    [bool]$Memory = $false,
    
    [Parameter(Mandatory=$false)]
    [bool]$Quiesce = $false,
    
    [Parameter(Mandatory=$false)]
    [PSCredential]$Credential
)

#region Functions
function Get-SnapshotReport {
    Write-Host "📊 Generating snapshot report..." -ForegroundColor Cyan
    
    $allSnapshots = Get-VM | Get-Snapshot | Select-Object @{
        Name='VMName'; Expression={$_.VM.Name}
    }, Name, Description, Created, @{
        Name='SizeGB'; Expression={[math]::Round($_.SizeGB, 2)}
    }, @{
        Name='AgeInDays'; Expression={((Get-Date) - $_.Created).Days}
    }, @{
        Name='IsCurrent'; Expression={$_.IsCurrent}
    }, @{
        Name='PowerState'; Expression={$_.PowerState}
    }
    
    # Group by age
    $oldSnapshots = $allSnapshots | Where-Object { $_.AgeInDays -gt $DaysOld }
    $largeSnapshots = $allSnapshots | Where-Object { $_.SizeGB -gt 10 }
    
    # Generate HTML report
    $htmlReport = @"
<!DOCTYPE html>
<html>
<head>
    <title>VMware Snapshot Report - $(Get-Date -Format 'yyyy-MM-dd')</title>
    <style>
        body { 
            font-family: 'Segoe UI', Arial; 
            background: linear-gradient(135deg, #00c6fb 0%, #005bea 100%);
            padding: 20px;
        }
        .container { 
            max-width: 1400px; 
            margin: 0 auto; 
            background: white; 
            padding: 30px; 
            border-radius: 15px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.2);
        }
        h1 { 
            color: #2c3e50; 
            border-bottom: 3px solid #3498db; 
            padding-bottom: 10px;
        }
        .alert {
            background: #fff3cd;
            border: 1px solid #ffc107;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
        }
        .stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin: 30px 0;
        }
        .stat-box {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 10px;
            text-align: center;
        }
        .stat-number {
            font-size: 2.5em;
            font-weight: bold;
            color: #2c3e50;
        }
        .stat-label {
            color: #6c757d;
            margin-top: 5px;
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
        }
        th { 
            background: #34495e; 
            color: white; 
            padding: 12px; 
            text-align: left;
        }
        td { 
            padding: 10px; 
            border-bottom: 1px solid #dee2e6;
        }
        tr:hover { background: #f8f9fa; }
        .old-snapshot { background: #ffebee; }
        .large-snapshot { background: #fff8e1; }
        .footer {
            text-align: center;
            margin-top: 30px;
            color: #6c757d;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>📸 VMware Snapshot Report</h1>
        <p><strong>vCenter:</strong> $vCenter | <strong>Generated:</strong> $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')</p>
        <p><strong>Generated by:</strong> Aykut Yıldız</p>
        
        <div class="stats">
            <div class="stat-box">
                <div class="stat-number">$($allSnapshots.Count)</div>
                <div class="stat-label">Total Snapshots</div>
            </div>
            <div class="stat-box">
                <div class="stat-number">$([math]::Round(($allSnapshots | Measure-Object SizeGB -Sum).Sum, 2)) GB</div>
                <div class="stat-label">Total Size</div>
            </div>
            <div class="stat-box">
                <div class="stat-number">$($oldSnapshots.Count)</div>
                <div class="stat-label">Old Snapshots (>$DaysOld days)</div>
            </div>
            <div class="stat-box">
                <div class="stat-number">$($largeSnapshots.Count)</div>
                <div class="stat-label">Large Snapshots (>10GB)</div>
            </div>
        </div>
"@

    if ($oldSnapshots.Count -gt 0) {
        $htmlReport += @"
        <div class="alert">
            ⚠️ <strong>Warning:</strong> Found $($oldSnapshots.Count) snapshots older than $DaysOld days that should be reviewed for deletion.
        </div>
"@
    }

    $htmlReport += @"
        <h2>Snapshot Details</h2>
        <table>
            <thead>
                <tr>
                    <th>VM Name</th>
                    <th>Snapshot Name</th>
                    <th>Description</th>
                    <th>Created</th>
                    <th>Age (Days)</th>
                    <th>Size (GB)</th>
                    <th>Current</th>
                </tr>
            </thead>
            <tbody>
"@

    foreach ($snapshot in $allSnapshots | Sort-Object AgeInDays -Descending) {
        $rowClass = if ($snapshot.AgeInDays -gt $DaysOld) { 'class="old-snapshot"' }
                   elseif ($snapshot.SizeGB -gt 10) { 'class="large-snapshot"' }
                   else { '' }
        
        $htmlReport += @"
                <tr $rowClass>
                    <td><strong>$($snapshot.VMName)</strong></td>
                    <td>$($snapshot.Name)</td>
                    <td>$($snapshot.Description)</td>
                    <td>$($snapshot.Created.ToString('yyyy-MM-dd HH:mm'))</td>
                    <td>$($snapshot.AgeInDays)</td>
                    <td>$($snapshot.SizeGB)</td>
                    <td>$(if($snapshot.IsCurrent){'✅'}else{''})</td>
                </tr>
"@
    }

    $htmlReport += @"
            </tbody>
        </table>
        
        <div class="footer">
            <p>VMware Snapshot Manager v1.5 | IT Admin Toolkit</p>
        </div>
    </div>
</body>
</html>
"@

    $reportFile = "C:\VMReports\SnapshotReport_$(Get-Date -Format 'yyyyMMdd_HHmmss').html"
    New-Item -ItemType Directory -Path "C:\VMReports" -Force -ErrorAction SilentlyContinue | Out-Null
    $htmlReport | Out-File -FilePath $reportFile -Encoding UTF8
    
    Write-Host "✅ Report saved: $reportFile" -ForegroundColor Green
    Start-Process $reportFile
    
    return $allSnapshots
}

function New-VMSnapshot {
    param([string[]]$VMs)
    
    foreach ($vm in $VMs) {
        try {
            Write-Host "📸 Creating snapshot for $vm..." -ForegroundColor Cyan
            
            $vmObj = Get-VM -Name $vm -ErrorAction Stop
            
            New-Snapshot -VM $vmObj `
                        -Name $SnapshotName `
                        -Description $Description `
                        -Memory:$Memory `
                        -Quiesce:$Quiesce `
                        -Confirm:$false
            
            Write-Host "   ✅ Snapshot created successfully" -ForegroundColor Green
        }
        catch {
            Write-Host "   ❌ Failed: $_" -ForegroundColor Red
        }
    }
}

function Remove-OldSnapshots {
    Write-Host "🗑️ Cleaning up old snapshots..." -ForegroundColor Yellow
    
    $oldSnapshots = Get-VM | Get-Snapshot | Where-Object {
        ((Get-Date) - $_.Created).Days -gt $DaysOld
    }
    
    if ($oldSnapshots.Count -eq 0) {
        Write-Host "   ✅ No old snapshots found" -ForegroundColor Green
        return
    }
    
    Write-Host "   Found $($oldSnapshots.Count) snapshots older than $DaysOld days" -ForegroundColor Yellow
    
    foreach ($snapshot in $oldSnapshots) {
        try {
            Write-Host "   Removing: $($snapshot.VM.Name) - $($snapshot.Name)" -ForegroundColor Yellow
            Remove-Snapshot -Snapshot $snapshot -Confirm:$false
            Write-Host "      ✅ Removed" -ForegroundColor Green
        }
        catch {
            Write-Host "      ❌ Failed: $_" -ForegroundColor Red
        }
    }
}

function Invoke-SnapshotConsolidation {
    Write-Host "🔧 Checking for VMs needing consolidation..." -ForegroundColor Cyan
    
    $vmsNeedingConsolidation = Get-VM | Where-Object {
        $_.ExtensionData.Runtime.ConsolidationNeeded
    }
    
    if ($vmsNeedingConsolidation.Count -eq 0) {
        Write-Host "   ✅ No VMs need consolidation" -ForegroundColor Green
        return
    }
    
    foreach ($vm in $vmsNeedingConsolidation) {
        try {
            Write-Host "   Consolidating: $($vm.Name)" -ForegroundColor Yellow
            $vm.ExtensionData.ConsolidateVMDisks()
            Write-Host "      ✅ Consolidated" -ForegroundColor Green
        }
        catch {
            Write-Host "      ❌ Failed: $_" -ForegroundColor Red
        }
    }
}
#endregion

#region Main
Write-Host @"
╔════════════════════════════════════════════════════════════╗
║         VMware Snapshot Management Tool v1.5               ║
║         PowerShell Automation by Aykut Yıldız             ║
╚════════════════════════════════════════════════════════════╝
"@ -ForegroundColor Cyan

# Load VMware PowerCLI
if (-not (Get-Module -ListAvailable -Name VMware.PowerCLI)) {
    Write-Host "Installing VMware PowerCLI..." -ForegroundColor Yellow
    Install-Module -Name VMware.PowerCLI -Scope CurrentUser -Force
}
Import-Module VMware.PowerCLI -ErrorAction SilentlyContinue

# Connect to vCenter
Write-Host ""
Write-Host "🔌 Connecting to vCenter: $vCenter" -ForegroundColor Cyan
try {
    if ($Credential) {
        Connect-VIServer -Server $vCenter -Credential $Credential -ErrorAction Stop | Out-Null
    } else {
        Connect-VIServer -Server $vCenter -ErrorAction Stop | Out-Null
    }
    Write-Host "✅ Connected successfully" -ForegroundColor Green
}
catch {
    Write-Host "❌ Connection failed: $_" -ForegroundColor Red
    return
}

Write-Host ""

# Execute operation
switch ($Operation) {
    "Create" {
        if (-not $VMName) {
            Write-Host "❌ VM name(s) required for create operation" -ForegroundColor Red
        } else {
            New-VMSnapshot -VMs $VMName
        }
    }
    
    "Delete" {
        if ($VMName) {
            foreach ($vm in $VMName) {
                $snapshots = Get-VM -Name $vm | Get-Snapshot
                foreach ($snap in $snapshots) {
                    Write-Host "Removing snapshot: $($snap.Name) from $vm" -ForegroundColor Yellow
                    Remove-Snapshot -Snapshot $snap -Confirm:$false
                }
            }
        } else {
            Write-Host "❌ VM name(s) required for delete operation" -ForegroundColor Red
        }
    }
    
    "Report" {
        Get-SnapshotReport
    }
    
    "Cleanup" {
        Remove-OldSnapshots
    }
    
    "Consolidate" {
        Invoke-SnapshotConsolidation
    }
}

# Disconnect from vCenter
Write-Host ""
Write-Host "🔌 Disconnecting from vCenter..." -ForegroundColor Cyan
Disconnect-VIServer -Confirm:$false

Write-Host "✅ Operation completed!" -ForegroundColor Green
#endregion
